<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Huebeiro.BrazilianCup.Domain\Huebeiro.BrazilianCup.Domain.csproj" />
    <ProjectReference Include="..\Huebeiro.BrazilianCup.Scraper\Huebeiro.BrazilianCup.Scraper.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
